// <auto-generated />
namespace AssetTracker.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v00));
        
        string IMigrationMetadata.Id
        {
            get { return "201612130738437_v00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
